services:
  api:
    container_name: anomalyze-api
    image: anomalyze-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - mongodb-test  # Ensure test DB is also available
    environment:
      - MONGO_URI=mongodb://mongodb:27017/anomalyze
      - TEST_MONGO_URI=mongodb://mongodb-test:27017/anomalyze_test  # Add test DB connection
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 

  mongodb:
    container_name: anomalyze-mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongodb-test:
    container_name: anomalyze-mongodb-test
    image: mongo:5.0
    ports:
      - "27018:27018"  # Test database runs on a different port
    volumes:
      - mongo_test_data:/data/db

volumes:
  mongo_data:
  mongo_test_data:
