services:
  api:
    container_name: anomalyze-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/anomalyze
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  mongodb:
    container_name: anomalyze-mongo
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data: