services:
  api:
    container_name: anomalyze-api
    image: anomalyze-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/anomalyze
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 

  mongodb:
    container_name: anomalyze-mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
