version: '3.8'

services:
  anomalyze-api:
    build: .
    container_name: anomalyze
    working_dir: /workspace  # Ensures the workspace is mounted correctly
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy  # Ensures MongoDB is ready before starting the API
    env_file:
      - .env
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_HOST: anomalyze-mongo
      MONGO_PORT: 27017

  mongodb:
    image: mongo:5.0
    container_name: anomalyze-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mongo_data:
    driver: local
