

services:
  api:
    container_name: anomalyze-api
    image: anomalyze-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - mongodb-test  # Ensure test DB is also available
    env_file:
      - .env  # Automatically load environment variables
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 

  mongodb:
    container_name: anomalyze-mongodb
    image: mongo:5.0
    restart: always
    ports:
      - "0.0.0.0:0:27017"  # Let Docker assign an available port dynamically

    environment:
      MONGO_INITDB_ROOT_USERNAME: anomalyze
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
      MONGO_INITDB_DATABASE: anomalyze
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js  # Load initialization script

  mongodb-test:
    container_name: anomalyze-mongodb-test
    image: mongo:5.0
    restart: always
    ports:
      - "27018:27017"  # Map test MongoDB port to 27017 internally
    environment:
      MONGO_INITDB_ROOT_USERNAME: anomalyze
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
      MONGO_INITDB_DATABASE: anomalyze_test
    volumes:
      - mongo_test_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js  # Ensure test DB gets the user

volumes:
  mongo_data:
  mongo_test_data:
