name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb-test:
        image: mongo:5.0
        ports:
          - 27018:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pymongo

      - name: Run Tests with Test DB
        env:
          TEST_MODE: "true"
          TEST_MONGO_URI: "mongodb://localhost:27018/anomalyze_test"
        run: pytest tests/

  build-and-push-docker:
    needs: test  # Runs only if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/anomalyze-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/anomalyze-backend:latest
